name: cicd
on:
  workflow_dispatch:
    inputs:
      enviornment:
        description: This is the enviornment value where the workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
            - dev
            - staging
            - prod

  
jobs:
# Every job needs separate runneer, it is called parallesim
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "Docker container build"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "test the container"
  deploy:
    if: inputs.enviornment=='dev'
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the container
        run: echo "Docker compose deploy the app"
    
